import Head from 'next/head'
import { createTheme, ThemeProvider } from '@mui/material/styles'
import { esES } from '@mui/material/locale'
import '@/styles/globals.css'
import Layout from '@/components/Layout'



const theme = createTheme(
  {
    palette: {
      primary: {
        light: '#757ce8',
        main: '#282c36',
        dark: '#002884',
        contrastText: '#fff',
      },
      secondary: {
        light: '#ff7961',
        main: '#f44336',
        dark: '#ba000d',
        contrastText: '#000',
      },
    }
  }, esES)


export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Landscape Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Layout>
            <Component {...pageProps} />
        </Layout>
      </ThemeProvider>

    </>

  )
}
